name: Auto Update Files
on:
  push:
    paths:
      - 'templates/client-data.xlsx'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          python generate_files.py
          git commit -am "Auto-update" && git push
