name: Generate JSON/YAML from XLSX and Update Sitemap

on:
  push:
    paths:
      - 'templates/*.xlsx'

jobs:
  generate-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pandas openpyxl PyYAML

      - name: Get Changed XLSX Files
        id: get_files
        env:
          PAYLOAD: ${{ toJson(github.event) }}
        run: |
          echo "Parsing push event for changed files..."
          # Extract added/modified files from push event
          ADDED_MODIFIED=$(echo "$PAYLOAD" | jq -r '.commits[].added[], .commits[].modified[]' | grep '^templates/.*\.xlsx$' || true)
          echo "changed_xlsx=$ADDED_MODIFIED" >> $GITHUB_ENV
          echo "📄 Detected XLSX files:"
          echo "$ADDED_MODIFIED"

      - name: Process Each XLSX File
        if: env.changed_xlsx != ''
        run: |
          echo "Processing files..."
          while IFS= read -r xlsx_file; do
            if [ -n "$xlsx_file" ] && [ -f "$xlsx_file" ]; then
              echo "⚙️ Processing: $xlsx_file"
              python ai-generators/generate_files_from_xlsx.py --input "$xlsx_file"
            else
              echo "⚠️ Skipped (file not found or empty): $xlsx_file"
            fi
          done <<< "${{ env.changed_xlsx }}"

      - name: Generate or Update Sitemap
        run: |
          python generate_sitemaps.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "Auto-generate files from XLSX and update sitemap" || echo "⏭️ No changes to commit"
          git push
