name: Generate JSON/YAML from XLSX and Update Sitemap

on:
  push:
    branches:
      - main  # or 'master' — adjust if needed
    paths:
      - 'templates/*.xlsx'

jobs:
  generate-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pandas openpyxl PyYAML

      - name: Get Changed XLSX Files via Git Diff
        id: get_files
        run: |
          echo "📄 Comparing against base commit: ${{ github.event.before }}"
          # Fallback: if before is all zeros (initial commit), compare to empty tree
          BEFORE_COMMIT=${{ github.event.before }}
          if [[ "$BEFORE_COMMIT" == "0000000000000000000000000000000000000000" ]]; then
            BEFORE_COMMIT=4b825dc642cb6eb9a060e54bf8d69288fbee4904  # empty tree hash
          fi

          # Get list of added/modified xlsx files in templates/
          CHANGED_FILES=$(git diff --name-only --diff-filter=AM "$BEFORE_COMMIT" HEAD | grep '^templates/.*\.xlsx$' || true)

          if [ -z "$CHANGED_FILES" ]; then
            echo "⚠️ No .xlsx files detected in templates/ in this push."
          else
            echo "✅ Detected changed XLSX files:"
            echo "$CHANGED_FILES"
          fi

          echo "changed_xlsx=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Process Each XLSX File
        if: env.changed_xlsx != ''
        run: |
          echo "⚙️ Processing detected XLSX files..."
          while IFS= read -r xlsx_file; do
            if [ -n "$xlsx_file" ] && [ -f "$xlsx_file" ]; then
              echo "📄 Processing: $xlsx_file"
              python ai-generators/generate_files_from_xlsx.py --input "$xlsx_file"
            else
              echo "❌ ERROR: File not found: '$xlsx_file'"
            fi
          done <<< "${{ env.changed_xlsx }}"

      - name: Verify Generated Files Exist
        run: |
          echo "🔍 Checking for generated files..."
          ls -la schema-files/organization/ || echo "📁 Directory not found or empty"
          echo "---"
          echo "📄 ai-sitemap.xml preview:"
          head -n 10 ai-sitemap.xml || echo "sitemap not found"

      - name: Configure Git & Attach to Branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git switch --detach ${{ github.ref_name }}

      - name: Commit and Push Changes
        run: |
          git add .
          git status
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Auto-generate files from XLSX and update sitemap"
            git push origin ${{ github.ref_name }}
            echo "✅ Push successful!"
          else
            echo "⏭️ No changes to commit."
          fi
