name: Generate JSON/YAML from XLSX and Update Sitemap

on:
  push:
    branches:
      - main
    paths:
      - 'templates/*.xlsx'

jobs:
  generate-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pandas openpyxl PyYAML

      - name: Get Changed XLSX Files via Git Diff
        id: get_files
        run: |
          echo "📄 Comparing against base commit: ${{ github.event.before }}"
          BEFORE_COMMIT=${{ github.event.before }}
          if [[ "$BEFORE_COMMIT" == "0000000000000000000000000000000000000000" ]]; then
            BEFORE_COMMIT=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          fi

          CHANGED_FILES=$(git diff --name-only --diff-filter=AM "$BEFORE_COMMIT" HEAD | grep '^templates/.*\.xlsx$' || true)

          if [ -z "$CHANGED_FILES" ]; then
            echo "⚠️ No .xlsx files detected in templates/ in this push."
          else
            echo "✅ Detected changed XLSX files:"
            echo "$CHANGED_FILES"
          fi

          echo "changed_xlsx=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Process Each XLSX File
        if: env.changed_xlsx != ''
        run: |
          echo "⚙️ Processing detected XLSX files..."
          while IFS= read -r xlsx_file; do
            if [ -n "$xlsx_file" ] && [ -f "$xlsx_file" ]; then
              echo "📄 Processing: $xlsx_file"
              python ai-generators/generate_files_from_xlsx.py --input "$xlsx_file"
            else
              echo "❌ ERROR: File not found: '$xlsx_file'"
            fi
          done <<< "${{ env.changed_xlsx }}"

      - name: Verify All Generated Files
        run: |
          echo "🔍 VERIFYING OUTPUTS — Listing all generated JSON/YAML files:"
          echo "=========================================================="
          find schema-files -type f KATEX_INLINE_OPEN -name "*.json" -o -name "*.yaml" KATEX_INLINE_CLOSE -exec ls -la {} \; | sort
          TOTAL_JSON=$(find schema-files -name "*.json" | wc -l)
          TOTAL_YAML=$(find schema-files -name "*.yaml" | wc -l)
          echo "----------------------------------------------------------"
          echo "✅ Total .json files generated: $TOTAL_JSON"
          echo "✅ Total .yaml files generated: $TOTAL_YAML"
          echo ""
          echo "📄 PREVIEW: ai-sitemap.xml (first 20 lines)"
          echo "=========================================================="
          head -n 20 ai-sitemap.xml 2>/dev/null || echo "❌ ai-sitemap.xml not found — check generate_sitemaps.py"

      - name: Generate or Update Sitemap
        run: |
          python generate_sitemaps.py

      - name: Configure Git & Attach to Branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git switch --detach ${{ github.ref_name }}

      - name: Commit and Push Changes
        run: |
          git add .
          git status
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Auto-generate files from XLSX and update sitemap"
            git push origin ${{ github.ref_name }}
            echo "✅ Push successful! All files committed."
          else
            echo "⏭️ No changes detected — nothing to commit or push."
          fi
